# Site settings
title: b1tByte 
description: "learning never exhausts the mind"
baseurl: "" # for test: remove string '/space-jekyll-template' to ''
url: "https://0xb1tbyte.github.io" # for test: remove string 'http://victorvoid.github.io' to '' but in production: 'https://yourusername.github.io'

# User settings
username: b1tByte
user_title: b1tByte
# email: lorem.lorem@ipsum.com
# twitter_username: loremipsum
github_username:  0xb1tbyte
# gplus_username:  loremipsum
linkedin_public_url:  # Example: For public profile 'www.linkedin.com/in/john-smith', 'john-smith' is your linkedin_public_url
# disqus_username: loremipsum
profile_picture: https://raw.githubusercontent.com/0xb1tByte/0xb1tbyte.github.io/master/assets/media/pic.jpg

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
links:
  section_1:
    - title: home
      url: /
      key_trigger: 1
    - title: my posts
      url: /posts
      key_trigger: 2
    - title: tags
      url: /tags
      key_trigger: 3
  section_2:
    - title: github
      url: 
      new_tab: true
      key_trigger: g



# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
